spring:
  application:
    name: toolsleasing

  datasource:
    url: jdbc:postgresql://192.168.1.102:50000/techjava2
    username: TechJava2
    password: TechJava2
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    properties:
      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation=true
#        dialect: org.hibernate.dialect.PostgreSQLDialect



